import { createFileRoute } from "@tanstack/react-router";

const LINES = [
  "# OpenOdia",
  "",
  "> Open source for the Odia language — tools, datasets, and AI resources for ଓଡ଼ିଆ.",
  "> Website: https://openodia.com",
  "",
  "## Pages",
  "",
  "- https://openodia.com — Home: ecosystem pillars (tools & libraries, models & datasets, community & learning), live counts, community videos, FAQ",
  "- https://openodia.com/tools — Unified directory: open-source Odia repos, datasets, models, libraries, fonts, and tools",
  "- https://openodia.com/models — Live registry of Odia AI models on Hugging Face (LLMs, ASR, TTS, translation, etc.)",
  "- https://openodia.com/datasets — Live browser of Odia datasets on Hugging Face (parallel corpora, speech, instruction tuning)",
  "- https://openodia.com/tutorials — YouTube tutorials from @openodia and related Odia AI channels",
  "- https://openodia.com/events — Community events: conferences, workshops, hackathons; with RSS feed at /events-feed",
  "- https://openodia.com/leaderboard — Odia benchmark results (task × dataset × metric), from Hugging Face model-index blocks",
  "- https://openodia.com/papers — Research index for Odia NLP, from OpenAlex and arXiv, tagged by task",
  "- https://openodia.com/treebank — Concordance search over the UD_Odia-ODTB Universal Dependencies treebank",
  "- https://openodia.com/playground — Odia NLP playground: run openodia in the browser via Pyodide",
  "- https://openodia.com/contribute — How to get a project, model, or dataset listed (metadata template)",
  "- https://openodia.com/about — About OpenOdia and the community behind it",
  "- https://openodia.com/r/{gh|model|dataset}/{owner}/{name} — Per-resource permalink: license, freshness, citation, dataset preview",
  "- https://openodia.com/sitemap.xml — XML sitemap for search engines",
  "",
  "## APIs (JSON — ideal for programmatic access)",
  "",
  "- https://openodia.com/api/resources — Unified catalog: one deduplicated record per resource across all sources, with permalink, SPDX license, task, and size. Supports ?kind=&license=&author=&q=&limit=&offset=",
  "- https://openodia.com/api/awesome — Parsed Awesome-Odia-AI directory (categories, items, links)",
  "- https://openodia.com/api/datasets — Odia datasets on Hugging Face (live)",
  "- https://openodia.com/api/events — Community events fetched from Bevy chapters (GDG, TFUG, OdishaAI)",
  "- https://openodia.com/api/models — Odia AI models on Hugging Face (live)",
  "- https://openodia.com/api/pypi — OpenOdia PyPI package metadata (version, summary, release count)",
  "- https://openodia.com/api/repos — GitHub repos from odisha-ml, OdiagenAI, OdiaWikimedia, ofdn, OdiaNLP orgs",
  "- https://openodia.com/api/videos — YouTube videos from Odia AI channels",
  "- https://openodia.com/events-feed — RSS 2.0 feed of community events",
  "",
  "## Related resources",
  "",
  "- https://github.com/soumendrak/openodia-hub — This website's source code (MIT license)",
  "- https://pypi.org/project/openodia/ — OpenOdia Python package for Odia language processing",
  "- https://github.com/odisha-ml/Awesome-Odia-AI — Curated list of Odia AI resources; the source the directory reads",
  "- https://github.com/odisha-ml — GitHub organization for Odisha AI/ML community projects",
  "- https://www.youtube.com/@openodia — OpenOdia YouTube channel (tutorials in Odia & English)",
  "- https://github.com/OdiaGenAI — OdiaGenAI: Odia LLMs, ASR, and datasets",
  "- https://github.com/OdiaNLP — OdiaNLP: translation, corpora, embeddings, spelling correction",
  "- https://github.com/OdiaWikimedia — OdiaWikimedia: converters, wordlists, OCR",
  "- https://www.soumendrak.com — Site's original author",
  "",
  "## llms-full.txt",
  "",
  "For a comprehensive plain-text dump of all site content, see: https://openodia.com/llms-full.txt",
  "",
  "## Structured data (JSON-LD)",
  "",
  "The site uses schema.org markup embedded in each page. Key schemas:",
  "- Organization (OpenOdia project)",
  "- Person (Soumendra Kumar Sahoo, original author)",
  "- Dataset / SoftwareSourceCode (every /r/ resource permalink)",
  "- WebSite",
  "- BreadcrumbList (every page)",
  "- FAQPage (homepage: 7 Q&A pairs about Odia AI)",
  "- ItemList (tools directory)",
  "",
  "## Agent notes",
  "",
  "- This file follows the llms.txt standard (https://llmstxt.org/).",
  "- All API endpoints return JSON with CORS headers allowing cross-origin access.",
  "- The site is fully server-side rendered (SSR) via Cloudflare Workers.",
  "- robots.txt allows GPTBot, ClaudeBot, CCBot, Google-Extended, and Googlebot.",
  "- API endpoints under /api/ are disallowed for generic crawlers but fully accessible to agents.",
];

export const Route = createFileRoute("/llms/txt")({
  server: {
    handlers: {
      GET: () => {
        return new Response(LINES.join("\n"), {
          status: 200,
          headers: {
            "Content-Type": "text/plain; charset=utf-8",
            "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
          },
        });
      },
    },
  },
});
