import { createFileRoute } from "@tanstack/react-router";

const LINES = [
  "# OpenOdia",
  "",
  "> Open source for the Odia language — tools, datasets, and AI resources for ଓଡ଼ିଆ.",
  "> Website: https://openodia.com",
  "",
  "## Pages",
  "",
  "- https://openodia.com — Home: featured videos, three pillars (YouTube, PyPI, Awesome-Odia-AI), FAQ",
  "- https://openodia.com/projects — List of open-source Odia language projects and repos across odisha-ml and related orgs",
  "- https://openodia.com/tools — Curated tool directory parsed from Awesome-Odia-AI (60+ datasets, models, libraries)",
  "- https://openodia.com/tutorials — YouTube tutorials from @openodia and related Odia AI channels",
  "- https://openodia.com/events — Community events: conferences, workshops, hackathons; with RSS feed at /events-feed",
  "- https://openodia.com/about — About OpenOdia and Soumendra Kumar Sahoo",
  "- https://openodia.com/sitemap.xml — XML sitemap for search engines",
  "",
  "## APIs (JSON — ideal for programmatic access)",
  "",
  "- https://openodia.com/api/awesome — Parsed Awesome-Odia-AI directory (categories, items, links)",
  "- https://openodia.com/api/events — Community events fetched from Bevy chapters (GDG, TFUG, OdishaAI)",
  "- https://openodia.com/api/pypi — OpenOdia PyPI package metadata (version, summary, release count)",
  "- https://openodia.com/api/repos — GitHub repos from odisha-ml, OdiagenAI, OdiaWikimedia, ofdn, OdiaNLP orgs",
  "- https://openodia.com/api/videos — YouTube videos from Odia AI channels",
  "- https://openodia.com/events-feed — RSS 2.0 feed of community events",
  "",
  "## Related resources",
  "",
  "- https://github.com/soumendrak/openodia-hub — This website's source code (MIT license)",
  "- https://pypi.org/project/openodia/ — OpenOdia Python package for Odia language processing",
  "- https://github.com/odisha-ml/Awesome-Odia-AI — Curated list of 60+ Odia AI resources",
  "- https://github.com/odisha-ml — GitHub organization for Odisha AI/ML community projects",
  "- https://www.youtube.com/@openodia — OpenOdia YouTube channel (tutorials in Odia & English)",
  "- https://www.soumendrak.com — Maintainer's personal site",
  "",
  "## llms-full.txt",
  "",
  "For a comprehensive plain-text dump of all site content, see: https://openodia.com/llms-full.txt",
  "",
  "## Structured data (JSON-LD)",
  "",
  "The site uses schema.org markup embedded in each page. Key schemas:",
  "- Organization (OpenOdia project)",
  "- Person (Soumendra Kumar Sahoo, maintainer)",
  "- WebSite",
  "- BreadcrumbList (every page)",
  "- FAQPage (homepage: 7 Q&A pairs about Odia AI)",
  "- ItemList (projects and tools pages)",
  "",
  "## Agent notes",
  "",
  "- This file follows the llms.txt standard (https://llmstxt.com/).",
  "- All API endpoints return JSON with CORS headers allowing cross-origin access.",
  "- The site is fully server-side rendered (SSR) via Cloudflare Workers.",
  "- robots.txt allows GPTBot, ClaudeBot, CCBot, Google-Extended, and Googlebot.",
  "- API endpoints under /api/ are disallowed for generic crawlers but fully accessible to agents.",
];

export const Route = createFileRoute("/llms/txt")({
  server: {
    handlers: {
      GET: () => {
        return new Response(LINES.join("\n"), {
          status: 200,
          headers: {
            "Content-Type": "text/plain; charset=utf-8",
            "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
          },
        });
      },
    },
  },
});
