/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as EventsFeedRouteImport } from './routes/events-feed'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ApiVideosRouteImport } from './routes/api/videos'
import { Route as ApiReposRouteImport } from './routes/api/repos'
import { Route as ApiPypiRouteImport } from './routes/api/pypi'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiAwesomeRouteImport } from './routes/api/awesome'

const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsFeedRoute = EventsFeedRouteImport.update({
  id: '/events-feed',
  path: '/events-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosRoute = ApiVideosRouteImport.update({
  id: '/api/videos',
  path: '/api/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReposRoute = ApiReposRouteImport.update({
  id: '/api/repos',
  path: '/api/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPypiRoute = ApiPypiRouteImport.update({
  id: '/api/pypi',
  path: '/api/pypi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAwesomeRoute = ApiAwesomeRouteImport.update({
  id: '/api/awesome',
  path: '/api/awesome',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/events-feed': typeof EventsFeedRoute
  '/projects': typeof ProjectsRoute
  '/tools': typeof ToolsRoute
  '/tutorials': typeof TutorialsRoute
  '/api/awesome': typeof ApiAwesomeRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pypi': typeof ApiPypiRoute
  '/api/repos': typeof ApiReposRoute
  '/api/videos': typeof ApiVideosRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/events-feed': typeof EventsFeedRoute
  '/projects': typeof ProjectsRoute
  '/tools': typeof ToolsRoute
  '/tutorials': typeof TutorialsRoute
  '/api/awesome': typeof ApiAwesomeRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pypi': typeof ApiPypiRoute
  '/api/repos': typeof ApiReposRoute
  '/api/videos': typeof ApiVideosRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/events-feed': typeof EventsFeedRoute
  '/projects': typeof ProjectsRoute
  '/tools': typeof ToolsRoute
  '/tutorials': typeof TutorialsRoute
  '/api/awesome': typeof ApiAwesomeRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pypi': typeof ApiPypiRoute
  '/api/repos': typeof ApiReposRoute
  '/api/videos': typeof ApiVideosRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/events'
    | '/events-feed'
    | '/projects'
    | '/tools'
    | '/tutorials'
    | '/api/awesome'
    | '/api/events'
    | '/api/pypi'
    | '/api/repos'
    | '/api/videos'
    | '/sitemap/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/events'
    | '/events-feed'
    | '/projects'
    | '/tools'
    | '/tutorials'
    | '/api/awesome'
    | '/api/events'
    | '/api/pypi'
    | '/api/repos'
    | '/api/videos'
    | '/sitemap/xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/events'
    | '/events-feed'
    | '/projects'
    | '/tools'
    | '/tutorials'
    | '/api/awesome'
    | '/api/events'
    | '/api/pypi'
    | '/api/repos'
    | '/api/videos'
    | '/sitemap/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EventsRoute: typeof EventsRoute
  EventsFeedRoute: typeof EventsFeedRoute
  ProjectsRoute: typeof ProjectsRoute
  ToolsRoute: typeof ToolsRoute
  TutorialsRoute: typeof TutorialsRoute
  ApiAwesomeRoute: typeof ApiAwesomeRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiPypiRoute: typeof ApiPypiRoute
  ApiReposRoute: typeof ApiReposRoute
  ApiVideosRoute: typeof ApiVideosRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events-feed': {
      id: '/events-feed'
      path: '/events-feed'
      fullPath: '/events-feed'
      preLoaderRoute: typeof EventsFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos': {
      id: '/api/videos'
      path: '/api/videos'
      fullPath: '/api/videos'
      preLoaderRoute: typeof ApiVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repos': {
      id: '/api/repos'
      path: '/api/repos'
      fullPath: '/api/repos'
      preLoaderRoute: typeof ApiReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pypi': {
      id: '/api/pypi'
      path: '/api/pypi'
      fullPath: '/api/pypi'
      preLoaderRoute: typeof ApiPypiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/awesome': {
      id: '/api/awesome'
      path: '/api/awesome'
      fullPath: '/api/awesome'
      preLoaderRoute: typeof ApiAwesomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EventsRoute: EventsRoute,
  EventsFeedRoute: EventsFeedRoute,
  ProjectsRoute: ProjectsRoute,
  ToolsRoute: ToolsRoute,
  TutorialsRoute: TutorialsRoute,
  ApiAwesomeRoute: ApiAwesomeRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiPypiRoute: ApiPypiRoute,
  ApiReposRoute: ApiReposRoute,
  ApiVideosRoute: ApiVideosRoute,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
