/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as EventsFeedRouteImport } from './routes/events-feed'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as LlmsTxtRouteImport } from './routes/llms.txt'
import { Route as LlmsFullTxtRouteImport } from './routes/llms-full.txt'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiVideosRouteImport } from './routes/api/videos'
import { Route as ApiRoadmapRouteImport } from './routes/api/roadmap'
import { Route as ApiReposRouteImport } from './routes/api/repos'
import { Route as ApiPypiRouteImport } from './routes/api/pypi'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiCommunityRouteImport } from './routes/api/community'
import { Route as ApiAwesomeRouteImport } from './routes/api/awesome'

const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsFeedRoute = EventsFeedRouteImport.update({
  id: '/events-feed',
  path: '/events-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsTxtRoute = LlmsTxtRouteImport.update({
  id: '/llms/txt',
  path: '/llms/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullTxtRoute = LlmsFullTxtRouteImport.update({
  id: '/llms-full/txt',
  path: '/llms-full/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosRoute = ApiVideosRouteImport.update({
  id: '/api/videos',
  path: '/api/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoadmapRoute = ApiRoadmapRouteImport.update({
  id: '/api/roadmap',
  path: '/api/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReposRoute = ApiReposRouteImport.update({
  id: '/api/repos',
  path: '/api/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPypiRoute = ApiPypiRouteImport.update({
  id: '/api/pypi',
  path: '/api/pypi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunityRoute = ApiCommunityRouteImport.update({
  id: '/api/community',
  path: '/api/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAwesomeRoute = ApiAwesomeRouteImport.update({
  id: '/api/awesome',
  path: '/api/awesome',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/events-feed': typeof EventsFeedRoute
  '/playground': typeof PlaygroundRoute
  '/roadmap': typeof RoadmapRoute
  '/tools': typeof ToolsRoute
  '/tutorials': typeof TutorialsRoute
  '/api/awesome': typeof ApiAwesomeRoute
  '/api/community': typeof ApiCommunityRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pypi': typeof ApiPypiRoute
  '/api/repos': typeof ApiReposRoute
  '/api/roadmap': typeof ApiRoadmapRoute
  '/api/videos': typeof ApiVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/llms-full/txt': typeof LlmsFullTxtRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/': typeof ApiIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/events-feed': typeof EventsFeedRoute
  '/playground': typeof PlaygroundRoute
  '/roadmap': typeof RoadmapRoute
  '/tools': typeof ToolsRoute
  '/tutorials': typeof TutorialsRoute
  '/api/awesome': typeof ApiAwesomeRoute
  '/api/community': typeof ApiCommunityRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pypi': typeof ApiPypiRoute
  '/api/repos': typeof ApiReposRoute
  '/api/roadmap': typeof ApiRoadmapRoute
  '/api/videos': typeof ApiVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/llms-full/txt': typeof LlmsFullTxtRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api': typeof ApiIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/events-feed': typeof EventsFeedRoute
  '/playground': typeof PlaygroundRoute
  '/roadmap': typeof RoadmapRoute
  '/tools': typeof ToolsRoute
  '/tutorials': typeof TutorialsRoute
  '/api/awesome': typeof ApiAwesomeRoute
  '/api/community': typeof ApiCommunityRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pypi': typeof ApiPypiRoute
  '/api/repos': typeof ApiReposRoute
  '/api/roadmap': typeof ApiRoadmapRoute
  '/api/videos': typeof ApiVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/llms-full/txt': typeof LlmsFullTxtRoute
  '/llms/txt': typeof LlmsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/': typeof ApiIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/events'
    | '/events-feed'
    | '/playground'
    | '/roadmap'
    | '/tools'
    | '/tutorials'
    | '/api/awesome'
    | '/api/community'
    | '/api/events'
    | '/api/pypi'
    | '/api/repos'
    | '/api/roadmap'
    | '/api/videos'
    | '/blog/$slug'
    | '/llms-full/txt'
    | '/llms/txt'
    | '/sitemap/xml'
    | '/api/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/events'
    | '/events-feed'
    | '/playground'
    | '/roadmap'
    | '/tools'
    | '/tutorials'
    | '/api/awesome'
    | '/api/community'
    | '/api/events'
    | '/api/pypi'
    | '/api/repos'
    | '/api/roadmap'
    | '/api/videos'
    | '/blog/$slug'
    | '/llms-full/txt'
    | '/llms/txt'
    | '/sitemap/xml'
    | '/api'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/events'
    | '/events-feed'
    | '/playground'
    | '/roadmap'
    | '/tools'
    | '/tutorials'
    | '/api/awesome'
    | '/api/community'
    | '/api/events'
    | '/api/pypi'
    | '/api/repos'
    | '/api/roadmap'
    | '/api/videos'
    | '/blog/$slug'
    | '/llms-full/txt'
    | '/llms/txt'
    | '/sitemap/xml'
    | '/api/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  EventsRoute: typeof EventsRoute
  EventsFeedRoute: typeof EventsFeedRoute
  PlaygroundRoute: typeof PlaygroundRoute
  RoadmapRoute: typeof RoadmapRoute
  ToolsRoute: typeof ToolsRoute
  TutorialsRoute: typeof TutorialsRoute
  ApiAwesomeRoute: typeof ApiAwesomeRoute
  ApiCommunityRoute: typeof ApiCommunityRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiPypiRoute: typeof ApiPypiRoute
  ApiReposRoute: typeof ApiReposRoute
  ApiRoadmapRoute: typeof ApiRoadmapRoute
  ApiVideosRoute: typeof ApiVideosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LlmsFullTxtRoute: typeof LlmsFullTxtRoute
  LlmsTxtRoute: typeof LlmsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiIndexRoute: typeof ApiIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events-feed': {
      id: '/events-feed'
      path: '/events-feed'
      fullPath: '/events-feed'
      preLoaderRoute: typeof EventsFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/txt': {
      id: '/llms/txt'
      path: '/llms/txt'
      fullPath: '/llms/txt'
      preLoaderRoute: typeof LlmsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full/txt': {
      id: '/llms-full/txt'
      path: '/llms-full/txt'
      fullPath: '/llms-full/txt'
      preLoaderRoute: typeof LlmsFullTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos': {
      id: '/api/videos'
      path: '/api/videos'
      fullPath: '/api/videos'
      preLoaderRoute: typeof ApiVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roadmap': {
      id: '/api/roadmap'
      path: '/api/roadmap'
      fullPath: '/api/roadmap'
      preLoaderRoute: typeof ApiRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repos': {
      id: '/api/repos'
      path: '/api/repos'
      fullPath: '/api/repos'
      preLoaderRoute: typeof ApiReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pypi': {
      id: '/api/pypi'
      path: '/api/pypi'
      fullPath: '/api/pypi'
      preLoaderRoute: typeof ApiPypiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/community': {
      id: '/api/community'
      path: '/api/community'
      fullPath: '/api/community'
      preLoaderRoute: typeof ApiCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/awesome': {
      id: '/api/awesome'
      path: '/api/awesome'
      fullPath: '/api/awesome'
      preLoaderRoute: typeof ApiAwesomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  EventsRoute: EventsRoute,
  EventsFeedRoute: EventsFeedRoute,
  PlaygroundRoute: PlaygroundRoute,
  RoadmapRoute: RoadmapRoute,
  ToolsRoute: ToolsRoute,
  TutorialsRoute: TutorialsRoute,
  ApiAwesomeRoute: ApiAwesomeRoute,
  ApiCommunityRoute: ApiCommunityRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiPypiRoute: ApiPypiRoute,
  ApiReposRoute: ApiReposRoute,
  ApiRoadmapRoute: ApiRoadmapRoute,
  ApiVideosRoute: ApiVideosRoute,
  BlogSlugRoute: BlogSlugRoute,
  LlmsFullTxtRoute: LlmsFullTxtRoute,
  LlmsTxtRoute: LlmsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiIndexRoute: ApiIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
